// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxCpBK1XF4zohrSlBKyaeF-EiQfwVJ13s',
    appId: '1:664807829025:web:56e2764b5567b3f6f87d60',
    messagingSenderId: '664807829025',
    projectId: 'smileyquiz-42b75',
    authDomain: 'smileyquiz-42b75.firebaseapp.com',
    storageBucket: 'smileyquiz-42b75.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb_IMr2-AWPQhOkMopb8Ej6K5V79vcSug',
    appId: '1:664807829025:android:27b5ed66a8b2befcf87d60',
    messagingSenderId: '664807829025',
    projectId: 'smileyquiz-42b75',
    storageBucket: 'smileyquiz-42b75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAufU5rumb0qNhf4CDlwADmsmfmlUsjnbw',
    appId: '1:664807829025:ios:0602288b0cb697f0f87d60',
    messagingSenderId: '664807829025',
    projectId: 'smileyquiz-42b75',
    storageBucket: 'smileyquiz-42b75.appspot.com',
    iosClientId: '664807829025-s6efkadsca82k4orndq9t42duf70ckkh.apps.googleusercontent.com',
    iosBundleId: 'com.codefox.quizzle',
  );
}
